#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app.swagger_ui:
  path: /api/v1/doc
  methods: GET
  controller: nelmio_api_doc.controller.swagger_ui

api_v1_auth:
  path: /api/v1/auth
  methods: ['POST']
